[tox]
env_list =
    lint
    mypy
    clean
    py{3.11,3.12,3.13,3.14}
    covcombine
    covreport

[testenv]
package = wheel
wheel_build_env = build_wheel
dependency_groups = test
commands = coverage run -m pytest -v {posargs}
depends =
    py{3.11,3.12,3.13,3.14}: clean
    covcombine: py{3.11,3.12,3.13,3.14}
    covreport: covcombine


[testenv:clean]
deps = coverage
skip_install = true
commands = coverage erase

[testenv:covcombine]
deps = coverage
skip_install = true
commands = coverage combine

[testenv:covreport]
deps = coverage
skip_install = true
commands_pre = coverage html --fail-under=0
commands = coverage report


[testenv:lint]
deps = pre-commit
skip_install = true
commands = pre-commit run -a


[testenv:lint_imports]
deps = import-linter
commands = lint-imports {posargs}


[testenv:docs]
basepython = python3.13
dependency_groups = docs
allowlist_externals = rm
changedir = docs/
# clean the build dir before rebuilding
commands_pre = rm -rf _build/
commands = sphinx-build -j auto -d "{temp_dir}/.doctrees" -b html -W . {posargs:{envdir}/doc_build}


[testenv:build]
deps = build
skip_install = true
commands = python -m build


[testenv:mypy]
deps = mypy
commands = mypy scmoosh.py tests/
